services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: djvrc_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    networks:
      - proxy_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: djvrc_api
    restart: unless-stopped
    env_file:
      - ./api/.env
    depends_on:
      - redis
    networks:
      - proxy_net

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: djvrc_worker
    restart: unless-stopped
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - ./api/.env
    depends_on:
      - redis
      - api
    networks:
      - proxy_net

  redis:
    image: redis:7-alpine
    container_name: djvrc_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proxy_net

volumes:
  redis_data:

networks:
  proxy_net:
    external: true